### ISSUE TITLE
Feature Request - Account to define ProvderId instead of AWSId

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/executor-cookiecutter#7]
## Expected Behavior

There should be consistency across Hamlet around the creation and usage of the `Account Id` in an accounts cmdb.

## Current Behavior

The current cookiecutter Account object defines an `AWSId`, however the [Executor has previously been updated](https://github.com/hamlet-io/executor-bash/blob/19a40e03d4593c7df0648f010fdc956b25b9547e/execution/setContext.sh#L196) to query for other provider values.

```json
{
    "Account" : {
        "Id" : "{{cookiecutter.account_id}}",
        "Name" : "{{cookiecutter.account_name}}",
        "Seed" : "{{cookiecutter.account_seed}}"
        {% if cookiecutter.account_type == "aws"  %}
        ,
        "AWSId" : "{{cookiecutter.aws_account_id}}"
        {% endif %}
    }
}
```

## Possible Solution

Refactor cookiecutter templates to implement the `ProviderId` attribute, established in hamlet-io/hamlet#1462

## Context

Maintaining individual attributes for each provider is untenable and unnecessary as we move forward with more provider plugins. A generic option is preferred, followed by providers implementing their own attributes as necessary.

**Comment by RossMurr4y** [comment]
This ticket to be actioned as a part of hamlet-io/engine#1462

**Comment by roleyfoley** [comment]
Added as part of registry updates
