### ISSUE TITLE
Feature Request - Azure Account CMDB's to Set Admin Group Attributes

### ISSUE THREAD

**Issue by RossMurr4y** [hamlet-io/executor-cookiecutter#9]
## Expected Behavior

When generating an Account CMDB that is for the Azure provider, an additional prompt should ask what the name for the AzureAdministratorsGroup should be.

## Current Behavior

Azure provider currently expects a setting with this information, but it should be made available through the Account configuration.

## Possible Solution

Requires implementation of https://github.com/hamlet-io/engine-plugin-azure/issues/120
Once an attribute is exposed on the Account layer for the Azure provider, the cookie cutter templates should include logic to prompt for and set this attribute only for Azure Account CMDBs

## Context

The baseline component in Azure will deploy a KeyVault for secret storage. This secret store requires a name for an existing administrators group in AAD that will be made the owners of the KeyVault.

**Comment by roleyfoley** [comment]
Done
